port: 7890
socks-port: 7891
external-controller: 127.0.0.1:9090

mode: rule

# info / warning / error / debug / silent
# log-level: info

# When set to false, resolver won't translate hostnames to IPv6 addresses
# ipv6: false

proxy-providers:
  tag:
    type: http
    url: "tag.url"
    interval: 3600
    path: ./tag.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204
  dler:
    type: http
    url: "dler.url"
    interval: 3600
    path: ./dler.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Singapore
      - Japan
      - Tag
      - Dler
      - DIRECT
  - name: Singapore
    type: select
    use:
      - tag
    filter: 新加坡
  - name: Japan
    type: select
    use:
      - tag
      - dler
    filter: 日本
  - name: Tag
    type: select
    use:
      - tag
  - name: Dler
    type: select
    use:
      - dler
  - name: Netflix
    type: select
    proxies:
      - Proxy
  - name: Disney
    type: select
    proxies:
      - Proxy
  - name: YouTube
    type: select
    proxies:
      - Proxy
  - name: Spotify
    type: select
    proxies:
      - Proxy
  - name: Apple
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Microsoft
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: PayPal
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Speedtest
    type: select
    proxies:
      - Proxy
      - DIRECT
  - name: Steam
    type: select
    proxies:
      - Proxy
      - DIRECT
  - name: Domestic
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Others
    type: select
    proxies:
      - Proxy
      - DIRECT


rule-providers:
  Special:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Special.yaml"
    path: ./Rules/Special
    interval: 86400
  PROXY:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Proxy.yaml"
    path: ./Rules/Proxy
    interval: 86400
  Domestic:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Domestic.yaml"
    path: ./Rules/Domestic
    interval: 86400
  Domestic IPs:
    type: http
    behavior: ipcidr
    url: "https://dler.cloud/Rules/Clash/Provider/Domestic%20IPs.yaml"
    path: ./Rules/Domestic_IPs
    interval: 86400
  LAN:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/LAN.yaml"
    path: ./Rules/LAN
    interval: 86400
  Netflix:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Netflix.yaml"
    path: ./Rules/Media/Netflix
    interval: 86400
  Spotify:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Spotify.yaml"
    path: ./Rules/Media/Spotify
    interval: 86400
  YouTube:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/YouTube.yaml"
    path: ./Rules/Media/YouTube
    interval: 86400
  Bilibili:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Bilibili.yaml"
    path: ./Rules/Media/Bilibili
    interval: 86400
  IQ:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/IQ.yaml"
    path: ./Rules/Media/IQI
    interval: 86400
  IQIYI:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/IQIYI.yaml"
    path: ./Rules/Media/IQYI
    interval: 86400
  Letv:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Letv.yaml"
    path: ./Rules/Media/Letv
    interval: 86400
  Netease Music:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Netease%20Music.yaml"
    path: ./Rules/Media/Netease_Music
    interval: 86400
  Tencent Video:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Tencent%20Video.yaml"
    path: ./Rules/Media/Tencent_Video
    interval: 86400
  Youku:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Youku.yaml"
    path: ./Rules/Media/Youku
    interval: 86400
  WeTV:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/WeTV.yaml"
    path: ./Rules/Media/WeTV
    interval: 86400
  ABC:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/ABC.yaml"
    path: ./Rules/Media/ABC
    interval: 86400
  Abema TV:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Abema%20TV.yaml"
    path: ./Rules/Media/Abema_TV
    interval: 86400
  Amazon:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Amazon.yaml"
    path: ./Rules/Media/Amazon
    interval: 86400
  Apple Music:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Apple%20Music.yaml"
    path: ./Rules/Media/Apple_Music
    interval: 86400
  Apple News:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Apple%20News.yaml"
    path: ./Rules/Media/Apple_News
    interval: 86400
  Apple TV:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Apple%20TV.yaml"
    path: ./Rules/Media/Apple_TV
    interval: 86400
  Bahamut:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Bahamut.yaml"
    path: ./Rules/Media/Bahamut
    interval: 86400
  BBC iPlayer:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/BBC%20iPlayer.yaml"
    path: ./Rules/Media/BBC_iPlayer
    interval: 86400
  DAZN:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/DAZN.yaml"
    path: ./Rules/Media/DAZN
    interval: 86400
  Discovery Plus:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Discovery%20Plus.yaml"
    path: ./Rules/Media/Discovery_Plus
    interval: 86400
  Disney Plus:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Disney%20Plus.yaml"
    path: ./Rules/Media/Disney_Plus
    interval: 86400
  encoreTVB:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/encoreTVB.yaml"
    path: ./Rules/Media/encoreTVB
    interval: 86400
  F1 TV:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/F1%20TV.yaml"
    path: ./Rules/Media/F1_TV
    interval: 86400
  Fox Now:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Fox%20Now.yaml"
    path: ./Rules/Media/Fox_Now
    interval: 86400
  Fox+:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Fox%2B.yaml"
    path: ./Rules/Media/Fox+
    interval: 86400
  HBO Go:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/HBO%20Go.yaml"
    path: ./Rules/Media/HBO_Go
    interval: 86400
  HBO Max:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/HBO%20Max.yaml"
    path: ./Rules/Media/HBO_Max
    interval: 86400
  Hulu Japan:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Hulu%20Japan.yaml"
    path: ./Rules/Media/Hulu_Japan
    interval: 86400
  Hulu:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Hulu.yaml"
    path: ./Rules/Media/Hulu
    interval: 86400
  Japonx:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Japonx.yaml"
    path: ./Rules/Media/Japonx
    interval: 86400
  JOOX:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/JOOX.yaml"
    path: ./Rules/Media/JOOX
    interval: 86400
  KKBOX:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/KKBOX.yaml"
    path: ./Rules/Media/KKBOX
    interval: 86400
  KKTV:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/KKTV.yaml"
    path: ./Rules/Media/KKTV
    interval: 86400
  Line TV:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Line%20TV.yaml"
    path: ./Rules/Media/Line_TV
    interval: 86400
  myTV SUPER:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/myTV%20SUPER.yaml"
    path: ./Rules/Media/myTV_SUPER
    interval: 86400
  Niconico:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Niconico.yaml"
    path: ./Rules/Media/Niconico
    interval: 86400
  Pandora:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Pandora.yaml"
    path: ./Rules/Media/Pandora
    interval: 86400
  PBS:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/PBS.yaml"
    path: ./Rules/Media/PBS
    interval: 86400
  Pornhub:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Pornhub.yaml"
    path: ./Rules/Media/Pornhub
    interval: 86400
  Soundcloud:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/Soundcloud.yaml"
    path: ./Rules/Media/Soundcloud
    interval: 86400
  ViuTV:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Media/ViuTV.yaml"
    path: ./Rules/Media/ViuTV
    interval: 86400
  Telegram:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Telegram.yaml"
    path: ./Rules/Telegram
    interval: 86400
  Crypto:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Crypto.yaml"
    path: ./Rules/Crypto
    interval: 86400
  Discord:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Discord.yaml"
    path: ./Rules/Discord
    interval: 86400
  Steam:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Steam.yaml"
    path: ./Rules/Steam
    interval: 86400
  Speedtest:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Speedtest.yaml"
    path: ./Rules/Speedtest
    interval: 86400
  PayPal:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/PayPal.yaml"
    path: ./Rules/PayPal
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Microsoft.yaml"
    path: ./Rules/Microsoft
    interval: 86400
  ChatGPT:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/ChatGPT.yaml"
    path: ./Rules/ChatGPT
    interval: 86400
  Apple:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Apple.yaml"
    path: ./Rules/Apple
    interval: 86400
  Google FCM:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Google%20FCM.yaml"
    path: ./Rules/Google FCM
    interval: 86400
  Scholar:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/Scholar.yaml"
    path: ./Rules/Scholar
    interval: 86400
  miHoYo:
    type: http
    behavior: classical
    url: "https://dler.cloud/Rules/Clash/Provider/miHoYo.yaml"
    path: ./Rules/miHoYo
    interval: 86400

rules:
  - RULE-SET,Special,DIRECT

  - RULE-SET,Netflix,Netflix
  - RULE-SET,Disney Plus,Disney
  - RULE-SET,YouTube,YouTube
  - RULE-SET,Spotify,Spotify

  - RULE-SET,Bilibili,DIRECT
  - RULE-SET,IQ,DIRECT
  - RULE-SET,IQIYI,DIRECT
  - RULE-SET,Letv,DIRECT
  - RULE-SET,Netease Music,DIRECT
  - RULE-SET,Tencent Video,DIRECT
  - RULE-SET,Youku,DIRECT
  - RULE-SET,WeTV,DIRECT

  - RULE-SET,ABC,Proxy
  - RULE-SET,Abema TV,Proxy
  - RULE-SET,Amazon,Proxy
  - RULE-SET,Bahamut,Proxy
  - RULE-SET,BBC iPlayer,Proxy
  - RULE-SET,DAZN,Proxy
  - RULE-SET,Discovery Plus,Proxy
  - RULE-SET,encoreTVB,Proxy
  - RULE-SET,F1 TV,Proxy
  - RULE-SET,Fox Now,Proxy
  - RULE-SET,Fox+,Proxy
  - RULE-SET,HBO Go,Proxy
  - RULE-SET,HBO Max,Proxy
  - RULE-SET,Hulu Japan,Proxy
  - RULE-SET,Hulu,Proxy
  - RULE-SET,Japonx,Proxy
  - RULE-SET,JOOX,Proxy
  - RULE-SET,KKBOX,Proxy
  - RULE-SET,KKTV,Proxy
  - RULE-SET,Line TV,Proxy
  - RULE-SET,myTV SUPER,Proxy
  - RULE-SET,Niconico,Proxy
  - RULE-SET,Pandora,Proxy
  - RULE-SET,PBS,Proxy
  - RULE-SET,Pornhub,Proxy
  - RULE-SET,Soundcloud,Proxy
  - RULE-SET,ViuTV,Proxy

  - RULE-SET,Apple Music,DIRECT
  - RULE-SET,Apple News,DIRECT
  - RULE-SET,Apple TV,DIRECT

  - RULE-SET,Apple,Apple

  - RULE-SET,Telegram,Proxy

  - RULE-SET,ChatGPT,Proxy
  - RULE-SET,Crypto,Proxy
  - RULE-SET,Discord,Proxy
  - RULE-SET,Google FCM,Proxy
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,PayPal,PayPal
  - RULE-SET,Scholar,Proxy
  - RULE-SET,Speedtest,Speedtest
  - RULE-SET,Steam,Steam

  - RULE-SET,miHoYo,DIRECT

  - RULE-SET,PROXY,Proxy

  - RULE-SET,Domestic,Domestic
  - RULE-SET,Domestic IPs,Domestic

  - RULE-SET,LAN,DIRECT
  - GEOIP,CN,Domestic
  - MATCH,Others
